import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, createHash, scryptSync, timingSafeEqual, createHmac } from 'node:crypto';
import { mkdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { lookup } from 'node:dns/promises';
import https from 'node:https';
const root=dirname(fileURLToPath(import.meta.url));
const config={port:Number(process.env.PORTAL_PORT||8082),host:process.env.PORTAL_HOST||'127.0.0.1',origin:process.env.PORTAL_PUBLIC_URL||'http://localhost:8082',gateway:process.env.PORTAL_GATEWAY_URL||'http://127.0.0.1:8081/api/gateway',serviceKey:process.env.PORTAL_GATEWAY_KEY||'',googleId:process.env.PORTAL_GOOGLE_CLIENT_ID||'',googleSecret:process.env.PORTAL_GOOGLE_CLIENT_SECRET||''};
const dbFile=process.env.PORTAL_DATABASE||join(root,'..','.local-data','portal.sqlite'); mkdirSync(dirname(dbFile),{recursive:true});
const db=new DatabaseSync(dbFile); db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password TEXT,google_subject TEXT UNIQUE,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS organizations(id TEXT PRIMARY KEY,owner TEXT NOT NULL,name TEXT NOT NULL,business TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'DRAFT');
CREATE TABLE IF NOT EXISTS apps(id TEXT PRIMARY KEY,org_id TEXT NOT NULL,name TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS systems(id TEXT PRIMARY KEY,org_id TEXT NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'OTHER',status TEXT NOT NULL DEFAULT 'ACTIVE',created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS app_systems(app_id TEXT PRIMARY KEY,system_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS api_keys(id TEXT PRIMARY KEY,app_id TEXT NOT NULL,mode TEXT NOT NULL,hash TEXT UNIQUE NOT NULL,prefix TEXT NOT NULL,revoked INTEGER NOT NULL DEFAULT 0,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS purchases(id TEXT PRIMARY KEY,app_id TEXT NOT NULL,mode TEXT NOT NULL,idem TEXT NOT NULL,fingerprint TEXT NOT NULL,amount INTEGER NOT NULL,currency TEXT NOT NULL,reference TEXT NOT NULL,status TEXT NOT NULL,response TEXT NOT NULL DEFAULT '{}',gateway_id TEXT,created TEXT NOT NULL,updated TEXT NOT NULL,UNIQUE(app_id,mode,idem));
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,app_id TEXT NOT NULL,mode TEXT NOT NULL,purchase_id TEXT,type TEXT NOT NULL,detail TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS hooks(id TEXT PRIMARY KEY,app_id TEXT NOT NULL,mode TEXT NOT NULL,url TEXT NOT NULL,secret TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS deliveries(id TEXT PRIMARY KEY,hook_id TEXT NOT NULL,event_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',attempts INTEGER NOT NULL DEFAULT 0,result TEXT,next_at INTEGER NOT NULL DEFAULT 0);
`);
const id=p=>`${p}_${randomBytes(16).toString('hex')}`, hash=s=>createHash('sha256').update(s).digest('hex'), now=()=>new Date().toISOString();
const one=(sql,...args)=>db.prepare(sql).get(...args), all=(sql,...args)=>db.prepare(sql).all(...args), run=(sql,...args)=>db.prepare(sql).run(...args);
function fail(status,message){throw Object.assign(new Error(message),{status});}
function required(value,label,max=200){if(typeof value!=='string'||!value.trim()||value.length>max)fail(400,`${label} is required (maximum ${max} characters)`);return value.trim();}
function modeOf(value){if(!['test','live'].includes(value))fail(400,'Mode must be test or live');return value;}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
async function body(req){let text='';for await(const chunk of req){text+=chunk;if(text.length>16384)fail(413,'Request too large');}try{return text?JSON.parse(text):{};}catch{fail(400,'Invalid JSON');}}
function user(req){const cookie=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('portal_session='))?.slice(15);const row=cookie&&one('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.hash=? AND s.expires>?',hash(cookie),Date.now());if(!row)fail(401,'Sign in to continue');return row;}
function session(res,uid){const token=randomBytes(32).toString('hex');run('INSERT INTO sessions VALUES(?,?,?)',hash(token),uid,Date.now()+8*3600000);res.setHeader('Set-Cookie',`portal_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800${config.origin.startsWith('https:')?'; Secure':''}`);}
function ownOrg(uid,org){const row=one('SELECT * FROM organizations WHERE id=? AND owner=?',org,uid);if(!row)fail(404,'Organization not found');return row;}
function ownApp(uid,app){const row=one('SELECT a.*,o.owner,o.status AS org_status FROM apps a JOIN organizations o ON o.id=a.org_id WHERE a.id=? AND o.owner=?',app,uid);if(!row)fail(404,'Application not found');return row;}
function addUser(email,name,password=null,google=null){const uid=id('usr');run('INSERT INTO users VALUES(?,?,?,?,?,?)',uid,email,name,password,google,now());const org=id('org');run('INSERT INTO organizations(id,owner,name) VALUES(?,?,?)',org,uid,`${name}'s business`);return uid;}
function event(app,mode,purchase,type,detail){const eid=id('evt');run('INSERT INTO events VALUES(?,?,?,?,?,?,?)',eid,app,mode,purchase,type,JSON.stringify(detail),now());if(purchase)for(const h of all('SELECT id FROM hooks WHERE app_id=? AND mode=? AND active=1',app,mode))run('INSERT INTO deliveries(id,hook_id,event_id) VALUES(?,?,?)',id('dlv'),h.id,eid);return eid;}
function safePurchase(p){return {...p,response:JSON.parse(p.response),fingerprint:undefined};}
const attempts=new Map(), oauthStates=new Map();
function rate(req){const ip=req.socket.remoteAddress;const record=attempts.get(ip)||{time:Date.now(),count:0};if(Date.now()-record.time>60000){record.time=Date.now();record.count=0;}record.count++;attempts.set(ip,record);if(record.count>30)fail(429,'Too many attempts. Try again in a minute.');}
function apiPrincipal(req){const token=req.headers.authorization?.match(/^Bearer (sk_(?:test|live)_[a-f0-9]+)$/)?.[1];const key=token&&one('SELECT k.*,a.org_id FROM api_keys k JOIN apps a ON a.id=k.app_id WHERE k.hash=? AND k.revoked=0',hash(token));if(!key)fail(401,'A valid integration secret key is required');return key;}
async function gateway(path,method='GET',data){if(!config.serviceKey)fail(503,'Portal-to-Gateway service key is not configured');const r=await fetch(config.gateway+path,{method,headers:{'Content-Type':'application/json','X-Portal-Service-Key':config.serviceKey},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(15000)});const payload=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error('Gateway rejected the request'),{gatewayStatus:r.status});return payload;}
async function purchase(app,mode,idem,b){required(idem,'Idempotency-Key',128);if(!Number.isSafeInteger(b.amountMinor)||b.amountMinor<=0||b.amountMinor>100000000000)fail(400,'amountMinor must be a positive integer, maximum 100000000000');const currency=required(b.currency,'Currency',3).toUpperCase();if(!['AFN','USD','EUR'].includes(currency))fail(400,'Supported currencies: AFN, USD, EUR');const reference=required(b.reference,'Order reference',120);const scenario=b.scenario||'approved';if(!['approved','declined','pending'].includes(scenario))fail(400,'Invalid sandbox scenario');if(Object.keys(b).some(k=>!['amountMinor','currency','reference','scenario'].includes(k)))fail(400,'Unexpected field. Do not submit card data through this API');
 const fingerprint=hash(JSON.stringify({amount:b.amountMinor,currency,reference,scenario}));const existing=one('SELECT * FROM purchases WHERE app_id=? AND mode=? AND idem=?',app,mode,idem);if(existing){if(existing.fingerprint!==fingerprint)fail(409,'Idempotency key already used with different parameters');return safePurchase(existing);}
 if(mode==='live')fail(503,'Live payment acceptance awaits certified APS funding and authentication integration; no transaction has been sent');
 const pid=id('pay');run('INSERT INTO purchases(id,app_id,mode,idem,fingerprint,amount,currency,reference,status,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?)',pid,app,mode,idem,fingerprint,b.amountMinor,currency,reference,'PROCESSING',now(),now());event(app,mode,pid,'purchase.created',{amountMinor:b.amountMinor,currency,reference});
 try{const reply=await gateway('/internal/portal/purchases','POST',{requestId:pid,idempotencyKey:hash(`${app}:${mode}:${idem}`),merchantId:`sandbox-${app}`,amountMinor:b.amountMinor,currency,scenario,mode});const status=['APPROVED','DECLINED','PENDING'].includes(reply.status)?reply.status:'PENDING';const safe={transactionId:reply.transactionId,status,responseCode:reply.responseCode,message:reply.message};run('UPDATE purchases SET status=?,response=?,gateway_id=?,updated=? WHERE id=?',status,JSON.stringify(safe),reply.transactionId||null,now(),pid);event(app,mode,pid,`purchase.${status.toLowerCase()}`,safe);}catch(e){const status=e.gatewayStatus?'FAILED':'PENDING';const response={message:e.gatewayStatus?'Gateway rejected request before acceptance':'Gateway response unavailable. Outcome is pending; do not submit a new payment.'};run('UPDATE purchases SET status=?,response=?,updated=? WHERE id=?',status,JSON.stringify(response),now(),pid);event(app,mode,pid,`purchase.${status.toLowerCase()}`,response);}
 return safePurchase(one('SELECT * FROM purchases WHERE id=?',pid));}
async function refresh(p){if(p.status!=='PENDING'&&p.status!=='PROCESSING')return safePurchase(p);try{const reply=await gateway(`/internal/portal/purchases/${p.id}`);if(reply.status!==p.status){const response={transactionId:reply.transactionId,status:reply.status,responseCode:reply.responseCode,message:reply.message};run('UPDATE purchases SET status=?,response=?,updated=? WHERE id=?',reply.status,JSON.stringify(response),now(),p.id);event(p.app_id,p.mode,p.id,`purchase.${reply.status.toLowerCase()}`,response);}}catch{}return safePurchase(one('SELECT * FROM purchases WHERE id=?',p.id));}
function publicIP(ip){return !ip.includes(':')&&!/^(0|10|127|169\.254|192\.168|172\.(1[6-9]|2\d|3[01])|100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])|198\.(18|19)|22[4-9]|23\d|24\d|25\d)\./.test(ip);}
async function deliver(d){const h=one('SELECT * FROM hooks WHERE id=? AND active=1',d.hook_id);if(!h)return;const ev=one('SELECT * FROM events WHERE id=?',d.event_id);const payload=JSON.stringify({...ev,detail:JSON.parse(ev.detail)}),t=Math.floor(Date.now()/1000),signature=createHmac('sha256',h.secret).update(`${t}.${payload}`).digest('hex');let result='Delivery failed',ok=false;try{const url=new URL(h.url);const addresses=await lookup(url.hostname,{all:true});if(!addresses.length||addresses.some(a=>!publicIP(a.address)))throw Error('Webhook host must resolve to public IPv4 addresses');result=await new Promise((resolve,reject)=>{const request=https.request(url,{method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload),'AfPay-Signature':`t=${t},v1=${signature}`},lookup:(_host,options,cb)=>options.all?cb(null,[addresses[0]]):cb(null,addresses[0].address,4),timeout:5000},r=>{r.resume();resolve(String(r.statusCode));});request.on('error',reject);request.on('timeout',()=>request.destroy(Error('Timeout')));request.end(payload);});ok=/^2\d\d$/.test(result);}catch(e){result=e.message;}const count=d.attempts+1;run('UPDATE deliveries SET attempts=?,status=?,result=?,next_at=? WHERE id=?',count,ok?'DELIVERED':count>=5?'FAILED':'RETRYING',result,Date.now()+30000*2**count,d.id);}
let dispatching=false;const worker=setInterval(async()=>{if(dispatching)return;dispatching=true;try{for(const d of all("SELECT * FROM deliveries WHERE status IN ('PENDING','RETRYING') AND next_at<=? LIMIT 10",Date.now()))await deliver(d);}finally{dispatching=false;}},5000);worker.unref();
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,config.origin),path=url.pathname;res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
 if(path==='/api/health')return json(res,200,{status:'ok'});
 if(path==='/api/config')return json(res,200,{googleEnabled:!!(config.googleId&&config.googleSecret),liveEnabled:false});
 if(!['GET','HEAD'].includes(req.method)&&!path.startsWith('/v1/')){if(req.headers.origin&&req.headers.origin!==config.origin)fail(403,'Origin rejected');if(req.headers['x-portal-request']!=='1')fail(403,'Portal request header required');}
 if(path==='/auth/google'){if(!config.googleId||!config.googleSecret)fail(503,'Google sign-in is not configured; use email registration');const state=randomBytes(32).toString('hex');oauthStates.set(hash(state),Date.now()+300000);res.setHeader('Set-Cookie',`oauth_state=${state}; HttpOnly; SameSite=Lax; Path=/; Max-Age=300`);res.writeHead(302,{Location:'https://accounts.google.com/o/oauth2/v2/auth?'+new URLSearchParams({client_id:config.googleId,redirect_uri:config.origin+'/auth/google/callback',response_type:'code',scope:'openid email profile',state})});return res.end();}
 if(path==='/auth/google/callback'){const state=url.searchParams.get('state')||'',cookie=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('oauth_state='))?.slice(12);const expires=oauthStates.get(hash(state));oauthStates.delete(hash(state));if(!expires||expires<Date.now()||cookie!==state)fail(400,'Invalid Google sign-in state');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:config.googleId,client_secret:config.googleSecret,code:url.searchParams.get('code')||'',redirect_uri:config.origin+'/auth/google/callback',grant_type:'authorization_code'}),signal:AbortSignal.timeout(10000)});const tokens=await r.json();if(!r.ok)fail(401,'Google sign-in failed');const info=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${tokens.access_token}`},signal:AbortSignal.timeout(10000)}).then(r=>r.json());if(!info.sub||!info.email_verified)fail(401,'Verified Google email required');let account=one('SELECT * FROM users WHERE google_subject=?',info.sub);if(!account&&one('SELECT id FROM users WHERE email=?',info.email.toLowerCase()))fail(409,'An email account already exists. Sign in with your password.');const uid=account?.id||addUser(info.email.toLowerCase(),info.name||info.email,null,info.sub);session(res,uid);res.writeHead(302,{Location:'/'});return res.end();}
 if(path==='/api/register'&&req.method==='POST'){rate(req);const b=await body(req),email=required(b.email,'Email').toLowerCase(),name=required(b.name,'Name',80),password=required(b.password,'Password',128);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<12)fail(400,'Use a valid email and a password of at least 12 characters');if(one('SELECT id FROM users WHERE email=?',email))fail(409,'Email already registered');const salt=randomBytes(16).toString('hex');const uid=addUser(email,name,`${salt}:${scryptSync(password,salt,64).toString('hex')}`);session(res,uid);return json(res,201,{id:uid});}
 if(path==='/api/login'&&req.method==='POST'){rate(req);const b=await body(req),email=required(b.email,'Email').toLowerCase(),password=required(b.password,'Password',128),account=one('SELECT * FROM users WHERE email=?',email);const [salt,expected]=(account?.password||`${'0'.repeat(32)}:${'0'.repeat(128)}`).split(':');if(!timingSafeEqual(scryptSync(password,salt,64),Buffer.from(expected,'hex'))||!account?.password)fail(401,'Email or password is incorrect');session(res,account.id);return json(res,200,{id:account.id});}
 if(path.startsWith('/v1/')){const key=apiPrincipal(req);const purchasePath=path==='/v1/purchases'||path==='/v1/payments/purchases';if(purchasePath&&req.method==='POST')return json(res,200,await purchase(key.app_id,key.mode,req.headers['idempotency-key'],await body(req)));if((purchasePath||path==='/v1/transactions')&&req.method==='GET')return json(res,200,all('SELECT * FROM purchases WHERE app_id=? AND mode=? ORDER BY created DESC LIMIT 500',key.app_id,key.mode).map(safePurchase));const pid=path.match(/^\/(?:v1\/purchases|v1\/transactions)\/(pay_[a-f0-9]+)$/)?.[1];if(pid&&req.method==='GET'){const p=one('SELECT * FROM purchases WHERE id=? AND app_id=? AND mode=?',pid,key.app_id,key.mode);if(!p)fail(404,'Transaction not found');return json(res,200,await refresh(p));}const op=/^\/v1\/(accounts\/balance|accounts\/title|payments\/(cash-in|cash-out|bills|topups|info|preauthorizations)|transfers\/(card-to-card|card-to-wallet|wallet-to-card))$/.test(path);if(op&&req.method==='POST'){const b=await body(req);if(!req.headers['idempotency-key'])fail(400,'Idempotency-Key is required');const result=await purchase(key.app_id,key.mode,req.headers['idempotency-key'],{amountMinor:Number(b.amount?.value?String(b.amount.value).replace('.',''):b.amountMinor||1),currency:b.amount?.currency||b.currency||'AFN',reference:b.merchantReference||`operation-${Date.now()}`,scenario:b.scenario||'approved'});return json(res,200,{...result,type:path.split('/').filter(Boolean).slice(1).join('_'),channel:b.channel||'server_api',cardPresence:b.cardPresence||'not_applicable'});}fail(404,'API route not found');}
 if(path.startsWith('/api/')){const u=user(req);if(path==='/api/me')return json(res,200,{id:u.id,email:u.email,name:u.name,organizations:all('SELECT * FROM organizations WHERE owner=?',u.id).map(o=>({...o,business:JSON.parse(o.business)}))});if(path==='/api/logout'&&req.method==='POST'){run('DELETE FROM sessions WHERE user_id=?',u.id);res.setHeader('Set-Cookie','portal_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0');return json(res,200,{ok:true});}
 if(path==='/api/organizations'&&req.method==='POST'){const b=await body(req),oid=id('org');run('INSERT INTO organizations(id,owner,name) VALUES(?,?,?)',oid,u.id,required(b.name,'Organization name'));return json(res,201,{id:oid});}
 let m=path.match(/^\/api\/organizations\/([^/]+)(?:\/(business|apps))?$/);if(m){const o=ownOrg(u.id,m[1]);if(m[2]==='business'&&req.method==='POST'){const b=await body(req);const business={legalName:required(b.legalName,'Legal name'),country:required(b.country,'Country'),registrationNumber:required(b.registrationNumber,'Registration number'),website:required(b.website,'Website')};run('UPDATE organizations SET business=?,status=? WHERE id=?',JSON.stringify(business),'SUBMITTED',o.id);return json(res,200,{status:'SUBMITTED'});}if(m[2]==='apps'){if(req.method==='GET')return json(res,200,all('SELECT * FROM apps WHERE org_id=? ORDER BY created DESC',o.id));if(req.method==='POST'){const b=await body(req),aid=id('app'),sid=id('sys'),name=required(b.name,'Application name');run('INSERT INTO apps VALUES(?,?,?,?)',aid,o.id,name,now());run('INSERT INTO systems VALUES(?,?,?,?,?,?)',sid,o.id,b.systemName||name,b.systemType||'OTHER','ACTIVE',now());run('INSERT INTO app_systems VALUES(?,?)',aid,sid);event(aid,'test',null,'application.created',{systemId:sid});return json(res,201,{id:aid,systemId:sid});}}}
 m=path.match(/^\/api\/apps\/([^/]+)\/(keys|purchases|events|webhooks|deliveries)(?:\/([^/]+))?$/);if(m){const a=ownApp(u.id,m[1]),mode=modeOf(url.searchParams.get('mode')||'test');if(m[2]==='keys'){if(req.method==='GET')return json(res,200,all('SELECT id,prefix,mode,revoked,created FROM api_keys WHERE app_id=? AND mode=?',a.id,mode));if(req.method==='POST'&&!m[3]){if(mode==='live')fail(403,'Live keys require approved production processing');const secret=`sk_${mode}_${randomBytes(32).toString('hex')}`,kid=id('key');run('INSERT INTO api_keys VALUES(?,?,?,?,?,?,?)',kid,a.id,mode,hash(secret),secret.slice(0,16),0,now());event(a.id,mode,null,'key.created',{id:kid});return json(res,201,{id:kid,secret});}if(req.method==='DELETE'&&m[3]){run('UPDATE api_keys SET revoked=1 WHERE id=? AND app_id=?',m[3],a.id);event(a.id,mode,null,'key.revoked',{id:m[3]});return json(res,200,{ok:true});}}
 if(m[2]==='purchases'){if(req.method==='GET'&&!m[3])return json(res,200,all('SELECT * FROM purchases WHERE app_id=? AND mode=? ORDER BY created DESC LIMIT 500',a.id,mode).map(safePurchase));if(req.method==='POST'&&!m[3]){if(mode!=='test')fail(403,'The console is sandbox only');return json(res,200,await purchase(a.id,mode,req.headers['idempotency-key'],await body(req)));}if(req.method==='GET'&&m[3]){const p=one('SELECT * FROM purchases WHERE id=? AND app_id=? AND mode=?',m[3],a.id,mode);if(!p)fail(404,'Purchase not found');return json(res,200,{...await refresh(p),events:all('SELECT * FROM events WHERE purchase_id=? ORDER BY created',p.id)});}}
 if(m[2]==='events'&&req.method==='GET')return json(res,200,all('SELECT * FROM events WHERE app_id=? AND mode=? ORDER BY created DESC LIMIT 500',a.id,mode));
 if(m[2]==='webhooks'){if(req.method==='GET')return json(res,200,all('SELECT id,url,mode,active,created FROM hooks WHERE app_id=? AND mode=?',a.id,mode));if(req.method==='POST'){const b=await body(req);let target;try{target=new URL(b.url);}catch{fail(400,'Valid HTTPS URL required');}if(target.protocol!=='https:'||target.username||target.password||target.port&&target.port!=='443')fail(400,'Use an HTTPS webhook on port 443');const hid=id('wh'),secret=`whsec_${randomBytes(32).toString('hex')}`;run('INSERT INTO hooks VALUES(?,?,?,?,?,?,?)',hid,a.id,mode,target.href,secret,1,now());return json(res,201,{id:hid,secret});}if(req.method==='DELETE'&&m[3]){run('UPDATE hooks SET active=0 WHERE id=? AND app_id=?',m[3],a.id);return json(res,200,{ok:true});}}
 if(m[2]==='deliveries'){if(req.method==='GET')return json(res,200,all('SELECT d.* FROM deliveries d JOIN hooks h ON h.id=d.hook_id WHERE h.app_id=? AND h.mode=? ORDER BY d.rowid DESC LIMIT 100',a.id,mode));if(req.method==='POST'&&m[3]){const d=one('SELECT d.* FROM deliveries d JOIN hooks h ON h.id=d.hook_id WHERE d.id=? AND h.app_id=?',m[3],a.id);if(!d)fail(404,'Delivery not found');run("UPDATE deliveries SET status='PENDING',attempts=0,next_at=0 WHERE id=?",d.id);return json(res,200,{ok:true});}}}fail(404,'Route not found');}
 const files={'/':['index.html','text/html'],'/index.html':['index.html','text/html'],'/app.js':['app.js','text/javascript'],'/styles.css':['styles.css','text/css']};const file=files[path];if(file&&req.method==='GET'){res.writeHead(200,{'Content-Type':file[1]+'; charset=utf-8','Cache-Control':'no-store'});return res.end(readFileSync(join(root,file[0])));}fail(404,'Not found');
 }catch(e){json(res,e.status||500,{message:e.status?e.message:'Request failed. Please try again.'});if(!e.status)console.error(e.message);}});
server.listen(config.port,config.host,()=>console.log(`Developer Portal: ${config.origin}`));
