package com.example.gateway

import jakarta.persistence.*
import jakarta.validation.constraints.NotBlank
import org.springframework.web.bind.annotation.*
import java.time.Instant
import java.util.UUID

@Entity @Table(name="developer_organizations") class DeveloperOrganization(@Id @GeneratedValue(strategy=GenerationType.UUID) var id:String?=null, @Column(nullable=false) var name:String, @Column(name="owner_subject") var ownerSubject:String?=null, var status:String="PENDING", @Column(nullable=false) var createdAt:Instant=Instant.now())
@Entity @Table(name="developer_apps") class DeveloperApp(@Id @GeneratedValue(strategy=GenerationType.UUID) var id:String?=null, @Column(nullable=false) var organizationId:String, @Column(nullable=false) var name:String, var status:String="SANDBOX", @Column(nullable=false) var scopes:String="", @Column(nullable=false) var createdAt:Instant=Instant.now())
@Entity @Table(name="developer_credentials") class DeveloperCredential(@Id @GeneratedValue(strategy=GenerationType.UUID) var id:String?=null, @Column(nullable=false) var appId:String, @Column(nullable=false) var clientId:String, @Column(nullable=false) var secretReference:String, var revoked:Boolean=false, @Column(nullable=false) var createdAt:Instant=Instant.now())
@Entity @Table(name="developer_certificates") class DeveloperCertificate(@Id @GeneratedValue(strategy=GenerationType.UUID) var id:String?=null, @Column(nullable=false) var appId:String, @Column(nullable=false) var thumbprint:String, @Column(nullable=false) var createdAt:Instant=Instant.now())
@Entity @Table(name="developer_webhooks") class DeveloperWebhook(@Id @GeneratedValue(strategy=GenerationType.UUID) var id:String?=null, @Column(nullable=false) var appId:String, @Column(nullable=false) var url:String, @Column(nullable=false) var events:String, @Column(nullable=false) var signingKeyReference:String, var active:Boolean=true)
@Entity @Table(name="developer_api_logs") class DeveloperApiLog(@Id @GeneratedValue(strategy=GenerationType.UUID) var id:String?=null,@Column(nullable=false) var appId:String,@Column(nullable=false) var eventType:String,@Column(nullable=false,length=1000) var detail:String,@Column(nullable=false) var createdAt:Instant=Instant.now())
@Entity @Table(name="developer_certification") class DeveloperCertification(@Id @GeneratedValue(strategy=GenerationType.UUID) var id:String?=null,@Column(nullable=false,unique=true) var appId:String,@Column(nullable=false) var applicationProfile:String="PENDING",@Column(nullable=false) var securityReview:String="PENDING",@Column(nullable=false) var sandboxTests:String="PENDING",@Column(nullable=false) var apsApproval:String="PENDING",@Column(nullable=false) var operationsApproval:String="PENDING",@Column(nullable=false) var productionCredentials:String="PENDING")
interface DeveloperOrganizationRepository:org.springframework.data.jpa.repository.JpaRepository<DeveloperOrganization,String>
interface DeveloperAppRepository:org.springframework.data.jpa.repository.JpaRepository<DeveloperApp,String>{ fun findByOrganizationId(organizationId:String):List<DeveloperApp> }
interface DeveloperCredentialRepository:org.springframework.data.jpa.repository.JpaRepository<DeveloperCredential,String>{ fun findByAppId(appId:String):List<DeveloperCredential> }
interface DeveloperCertificateRepository:org.springframework.data.jpa.repository.JpaRepository<DeveloperCertificate,String>{ fun findByAppId(appId:String):List<DeveloperCertificate> }
interface DeveloperWebhookRepository:org.springframework.data.jpa.repository.JpaRepository<DeveloperWebhook,String>{ fun findByAppId(appId:String):List<DeveloperWebhook> }
interface DeveloperApiLogRepository:org.springframework.data.jpa.repository.JpaRepository<DeveloperApiLog,String>{ fun findByAppIdOrderByCreatedAtDesc(appId:String):List<DeveloperApiLog> }
interface DeveloperCertificationRepository:org.springframework.data.jpa.repository.JpaRepository<DeveloperCertification,String>{ fun findByAppId(appId:String):DeveloperCertification? }
data class OrganizationRequest(@field:NotBlank val name:String)
data class AppRequest(@field:NotBlank val organizationId:String,@field:NotBlank val name:String)
data class CertificateRequest(@field:NotBlank val thumbprint:String)
data class WebhookRequest(@field:NotBlank val url:String,@field:NotBlank val events:String)
@RestController @RequestMapping("/api/v1/developer") class DeveloperPlatformController(private val organizations:DeveloperOrganizationRepository,private val apps:DeveloperAppRepository,private val credentials:DeveloperCredentialRepository,private val certificates:DeveloperCertificateRepository,private val webhooks:DeveloperWebhookRepository,private val logs:DeveloperApiLogRepository,private val certifications:DeveloperCertificationRepository){
 @GetMapping("/organizations") fun organizations()=organizations.findAll(); @PostMapping("/organizations") fun organization(@RequestBody r:OrganizationRequest)=organizations.save(DeveloperOrganization(name=r.name))
 @GetMapping("/apps") fun apps()=apps.findAll(); @PostMapping("/apps") fun app(@RequestBody r:AppRequest):DeveloperApp{require(organizations.existsById(r.organizationId)){"Organization not found"};return apps.save(DeveloperApp(organizationId=r.organizationId,name=r.name))}
 @GetMapping("/apps/{id}") fun app(@PathVariable id:String)=apps.findById(id).orElseThrow{IllegalArgumentException("Application not found")}; @PatchMapping("/apps/{id}") fun update(@PathVariable id:String,@RequestBody r:Map<String,String>):DeveloperApp{val a=app(id);r["name"]?.let{a.name=it};r["status"]?.let{a.status=it};return apps.save(a)} @DeleteMapping("/apps/{id}") fun deleteApp(@PathVariable id:String){apps.deleteById(id)}
 @GetMapping("/apps/{id}/credentials") fun credentials(@PathVariable id:String)=credentials.findByAppId(id); @PostMapping("/apps/{id}/credentials") fun credential(@PathVariable id:String):Map<String,String>{require(apps.existsById(id)){"Application not found"};val secret="secret_"+UUID.randomUUID().toString().replace("-","");val hash=org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder().encode(secret) ?: throw IllegalStateException("Credential hashing failed");val c=credentials.save(DeveloperCredential(appId=id,clientId="client_"+UUID.randomUUID().toString().take(12),secretReference=hash));return mapOf("id" to c.id!!,"clientId" to c.clientId,"secret" to secret)}
 @GetMapping("/apps/{id}/certificates") fun certificates(@PathVariable id:String)=certificates.findByAppId(id); @PostMapping("/apps/{id}/certificates") fun certificate(@PathVariable id:String,@RequestBody r:CertificateRequest)=certificates.save(DeveloperCertificate(appId=id,thumbprint=r.thumbprint))
 @DeleteMapping("/apps/{appId}/certificates/{id}") fun deleteCertificate(@PathVariable appId:String,@PathVariable id:String){certificates.deleteById(id)} @PutMapping("/apps/{id}/scopes") fun scopes(@PathVariable id:String,@RequestBody scopes:List<String>):DeveloperApp{val app=app(id);app.scopes=scopes.distinct().joinToString(" ");logs.save(DeveloperApiLog(appId=id,eventType="SCOPES_UPDATED",detail="Scopes updated"));return apps.save(app)}
 @GetMapping("/apps/{id}/webhooks") fun webhooks(@PathVariable id:String)=webhooks.findByAppId(id); @PostMapping("/apps/{id}/webhooks") fun webhook(@PathVariable id:String,@RequestBody r:WebhookRequest)=webhooks.save(DeveloperWebhook(appId=id,url=r.url,events=r.events,signingKeyReference="WEBHOOK_KEY_REF")); @DeleteMapping("/apps/{appId}/webhooks/{id}") fun deleteWebhook(@PathVariable appId:String,@PathVariable id:String){webhooks.deleteById(id)} @PostMapping("/webhooks/{id}/rotate-secret") fun rotate(@PathVariable id:String)=mapOf("webhookId" to id,"secret" to "whsec_"+UUID.randomUUID().toString().replace("-","")).also{logs.save(DeveloperApiLog(appId="UNKNOWN",eventType="WEBHOOK_SECRET_ROTATED",detail="Webhook $id rotated"))}
 @GetMapping("/logs") fun logs(@RequestParam appId:String)=logs.findByAppIdOrderByCreatedAtDesc(appId).map{mapOf("id" to it.id,"eventType" to it.eventType,"detail" to it.detail.replace(Regex("(?i)(secret|token|pan|cvv|pin)\\s*[:=]\\s*\\S+"),"[REDACTED]"),"createdAt" to it.createdAt)}
 @GetMapping("/certification") fun certification(@RequestParam appId:String)=certifications.findByAppId(appId)?:certifications.save(DeveloperCertification(appId=appId))
 @PatchMapping("/certification/{appId}") fun certification(@PathVariable appId:String,@RequestBody updates:Map<String,String>):DeveloperCertification{val item=certifications.findByAppId(appId)?:DeveloperCertification(appId=appId);updates["applicationProfile"]?.let{item.applicationProfile=it};updates["securityReview"]?.let{item.securityReview=it};updates["sandboxTests"]?.let{item.sandboxTests=it};updates["apsApproval"]?.let{item.apsApproval=it};updates["operationsApproval"]?.let{item.operationsApproval=it};updates["productionCredentials"]?.let{item.productionCredentials=it};return certifications.save(item)} }
