package com.example.gateway

import jakarta.persistence.*
import jakarta.validation.constraints.NotBlank
import org.springframework.stereotype.Service
import org.springframework.web.bind.annotation.*
import java.time.Instant

enum class ReconciliationStatus { MATCHED, LOCAL_ONLY, APS_ONLY, AMOUNT_MISMATCH, STATUS_MISMATCH, DUPLICATE, LATE_RESPONSE, REVERSAL_MISMATCH }
@Entity @Table(name = "reconciliation_imports") class ReconciliationImportEntity(@Id @GeneratedValue(strategy = GenerationType.UUID) var id: String? = null, @Column(nullable = false) var sourceName: String, @Column(nullable = false) var checksum: String, @Column(nullable = false) var businessDate: String, @Column(nullable = false) var createdAt: Instant = Instant.now())
@Entity @Table(name = "reconciliation_exceptions") class ReconciliationExceptionEntity(@Id @GeneratedValue(strategy = GenerationType.UUID) var id: String? = null, var transactionId: String? = null, @Enumerated(EnumType.STRING) @Column(nullable = false) var status: ReconciliationStatus, @Column(nullable = false, length = 1000) var detail: String, var assignedTo: String? = null, var resolvedAt: Instant? = null, @Column(nullable = false) var createdAt: Instant = Instant.now())
interface ReconciliationImportRepository : org.springframework.data.jpa.repository.JpaRepository<ReconciliationImportEntity, String>
interface ReconciliationExceptionRepository : org.springframework.data.jpa.repository.JpaRepository<ReconciliationExceptionEntity, String>
data class ReconciliationImportRequest(@field:NotBlank val sourceName: String, @field:NotBlank val checksum: String, @field:NotBlank val businessDate: String)
data class ReconciliationExceptionRequest(val transactionId: String? = null, val status: ReconciliationStatus, @field:NotBlank val detail: String)
data class ReconciliationMatchRequest(val transactionId: String?, @field:NotBlank val apsRrn: String, val amountMinor: Long?, val currency: String? = null)
@Service class ReconciliationService(private val imports: ReconciliationImportRepository, private val exceptions: ReconciliationExceptionRepository, private val payments: PaymentRepository) { fun ingest(r: ReconciliationImportRequest) = imports.save(ReconciliationImportEntity(sourceName = r.sourceName, checksum = r.checksum, businessDate = r.businessDate)); fun exception(r: ReconciliationExceptionRequest) = exceptions.save(ReconciliationExceptionEntity(transactionId = r.transactionId, status = r.status, detail = r.detail)); fun assign(id:String,operator:String):ReconciliationExceptionEntity{val item=exceptions.findById(id).orElseThrow{IllegalArgumentException("Exception not found")};item.assignedTo=operator;return exceptions.save(item)} fun resolve(id:String):ReconciliationExceptionEntity{val item=exceptions.findById(id).orElseThrow{IllegalArgumentException("Exception not found")};item.resolvedAt=Instant.now();return exceptions.save(item)} fun match(r: ReconciliationMatchRequest):Map<String,Any?>{val tx=r.transactionId?.let{payments.findById(it).orElse(null)};val status=when{tx==null->ReconciliationStatus.APS_ONLY;r.amountMinor!=null&&tx.amountMinor!=r.amountMinor->ReconciliationStatus.AMOUNT_MISMATCH;r.currency!=null&&tx.currency!=r.currency->ReconciliationStatus.STATUS_MISMATCH;else->ReconciliationStatus.MATCHED};if(status!=ReconciliationStatus.MATCHED)exception(ReconciliationExceptionRequest(r.transactionId,status,"APS RRN ${r.apsRrn} requires operations review"));return mapOf("status" to status,"transactionId" to r.transactionId,"apsRrn" to r.apsRrn)} fun imports() = imports.findAll(); fun exceptions() = exceptions.findAll() }
@RestController @RequestMapping("/api/v1") class ReconciliationController(private val service: ReconciliationService) { @PostMapping("/admin/reconciliation/imports") fun ingest(@RequestBody r: ReconciliationImportRequest) = service.ingest(r); @PostMapping("/admin/reconciliation/match") fun match(@RequestBody r: ReconciliationMatchRequest)=service.match(r); @GetMapping("/admin/reconciliation/imports") fun imports() = service.imports(); @PostMapping("/exceptions") fun exception(@RequestBody r: ReconciliationExceptionRequest) = service.exception(r); @GetMapping("/exceptions") fun exceptions() = service.exceptions(); @PostMapping("/exceptions/{id}/assign") fun assign(@PathVariable id:String,@RequestParam operator:String)=service.assign(id,operator); @PostMapping("/exceptions/{id}/resolve") fun resolve(@PathVariable id:String)=service.resolve(id) }
