import {test,after,before} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import http from 'node:http';
import {once} from 'node:events';
const base='http://127.0.0.1:18082',key='test-service-secret-with-more-than-32-characters';
const dir=mkdtempSync(join(tmpdir(),'afpay-portal-test-'));let processHandle,mock,alice,bob,appId,secondId,secret,pid;const calls=[];
async function request(path,{cookie,token,method='GET',body,idem,origin}={}){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json','X-Portal-Request':'1',...(cookie?{Cookie:cookie}:{}),...(token?{Authorization:`Bearer ${token}`} :{}),...(idem?{'Idempotency-Key':idem}:{}),...(origin?{Origin:origin}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
before(async()=>{mock=http.createServer(async(req,res)=>{assert.equal(req.headers['x-portal-service-key'],key);let text='';for await(const chunk of req)text+=chunk;const b=JSON.parse(text||'{}');calls.push(b);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({transactionId:b.requestId,status:b.scenario==='declined'?'DECLINED':b.scenario==='pending'?'PENDING':'APPROVED',responseCode:'000',message:'Sandbox'}));});mock.listen(18081,'127.0.0.1');await once(mock,'listening');processHandle=spawn(process.execPath,['server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORTAL_HOST:'127.0.0.1',PORTAL_PORT:'18082',PORTAL_PUBLIC_URL:base,PORTAL_DATABASE:join(dir,'portal.sqlite'),PORTAL_GATEWAY_URL:'http://127.0.0.1:18081',PORTAL_GATEWAY_KEY:key},stdio:'pipe'});for(let i=0;i<50;i++){try{if((await fetch(base+'/api/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Portal did not start');});
after(()=>{processHandle?.kill();mock?.close();});
test('registration, authentication and application ownership',async()=>{const a=await request('/api/register',{method:'POST',body:{name:'Alice',email:'alice@example.test',password:'LocalTestPassword123!'}});assert.equal(a.status,201);alice=a.cookie;const b=await request('/api/register',{method:'POST',body:{name:'Bob',email:'bob@example.test',password:'LocalTestPassword123!'}});bob=b.cookie;const me=await request('/api/me',{cookie:alice});const org=me.body.organizations[0].id;const app=await request(`/api/organizations/${org}/apps`,{cookie:alice,method:'POST',body:{name:'Store'}});appId=app.body.id;secondId=(await request(`/api/organizations/${org}/apps`,{cookie:alice,method:'POST',body:{name:'Other store'}})).body.id;assert.equal((await request(`/api/apps/${appId}/keys`,{cookie:bob})).status,404);assert.equal((await request('/api/me')).status,401);assert.equal((await request('/api/login',{method:'POST',body:{email:'alice@example.test',password:'WrongPassword123'}})).status,401);});
test('one-time hashed test key and locked live issuance',async()=>{const k=await request(`/api/apps/${appId}/keys`,{cookie:alice,method:'POST',body:{}});assert.equal(k.status,201);secret=k.body.secret;assert.match(secret,/^sk_test_/);const listing=await request(`/api/apps/${appId}/keys`,{cookie:alice});assert.ok(!JSON.stringify(listing.body).includes(secret));assert.equal((await request(`/api/apps/${appId}/keys?mode=live`,{cookie:alice,method:'POST',body:{}})).status,403);});
test('purchase reaches gateway and exact idempotency replay produces one call',async()=>{const body={amountMinor:5000,currency:'AFN',reference:'order-one',scenario:'approved'};const r=await request('/v1/purchases',{token:secret,method:'POST',idem:'order-one',body});assert.equal(r.status,200);assert.equal(r.body.status,'APPROVED');pid=r.body.id;assert.equal(calls.length,1);const replay=await request('/v1/purchases',{token:secret,method:'POST',idem:'order-one',body});assert.equal(replay.body.id,pid);assert.equal(calls.length,1);assert.equal((await request('/v1/purchases',{token:secret,method:'POST',idem:'order-one',body:{...body,amountMinor:10}})).status,409);assert.equal((await request(`/api/apps/${secondId}/purchases/${pid}`,{cookie:alice})).status,404);assert.equal((await request(`/api/apps/${appId}/purchases`,{cookie:bob})).status,404);const detail=await request(`/api/apps/${appId}/purchases/${pid}`,{cookie:alice});assert.equal(detail.body.events.length,2);});
test('concurrent idempotency, validation, CSRF, and key revocation',async()=>{const params={token:secret,method:'POST',idem:'parallel',body:{amountMinor:100,currency:'USD',reference:'parallel'}};const results=await Promise.all(Array.from({length:5},()=>request('/v1/purchases',params)));assert.equal(new Set(results.map(r=>r.body.id)).size,1);assert.equal(calls.length,2);assert.equal((await request('/v1/purchases',{...params,idem:'bad',body:{...params.body,pan:'4111111111111111'}})).status,400);assert.equal((await request(`/api/apps/${appId}/keys`,{cookie:alice,method:'POST',body:{},origin:'https://evil.example'})).status,403);const keys=await request(`/api/apps/${appId}/keys`,{cookie:alice});await request(`/api/apps/${appId}/keys/${keys.body[0].id}`,{cookie:alice,method:'DELETE'});assert.equal((await request('/v1/purchases',{token:secret})).status,401);});
test('business submission and webhook management are scoped',async()=>{const me=await request('/api/me',{cookie:alice});const org=me.body.organizations[0].id;const b=await request(`/api/organizations/${org}/business`,{cookie:alice,method:'POST',body:{legalName:'Store Ltd',country:'Afghanistan',registrationNumber:'REG-1',website:'https://example.com'}});assert.equal(b.body.status,'SUBMITTED');assert.equal((await request(`/api/apps/${appId}/webhooks`,{cookie:alice,method:'POST',body:{url:'http://localhost/secret'}})).status,400);const hook=await request(`/api/apps/${appId}/webhooks`,{cookie:alice,method:'POST',body:{url:'https://example.com/hook'}});assert.match(hook.body.secret,/^whsec_/);assert.equal((await request(`/api/apps/${appId}/webhooks`,{cookie:bob})).status,404);await request(`/api/apps/${appId}/webhooks/${hook.body.id}`,{cookie:alice,method:'DELETE'});});
